package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Magicking/rc-ge-ch-pdf/models"
)

// GetreceiptOKCode is the HTTP code returned for type GetreceiptOK
const GetreceiptOKCode int = 200

/*GetreceiptOK Fichier de reçu de l'horodatage certifié blockchain


swagger:response getreceiptOK
*/
type GetreceiptOK struct {

	/*
	  In: Body
	*/
	Payload runtime.File `json:"body,omitempty"`
}

// NewGetreceiptOK creates GetreceiptOK with default headers values
func NewGetreceiptOK() *GetreceiptOK {
	return &GetreceiptOK{}
}

// WithPayload adds the payload to the getreceipt o k response
func (o *GetreceiptOK) WithPayload(payload runtime.File) *GetreceiptOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getreceipt o k response
func (o *GetreceiptOK) SetPayload(payload runtime.File) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetreceiptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetreceiptDefault Internal error

swagger:response getreceiptDefault
*/
type GetreceiptDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetreceiptDefault creates GetreceiptDefault with default headers values
func NewGetreceiptDefault(code int) *GetreceiptDefault {
	if code <= 0 {
		code = 500
	}

	return &GetreceiptDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the getreceipt default response
func (o *GetreceiptDefault) WithStatusCode(code int) *GetreceiptDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the getreceipt default response
func (o *GetreceiptDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the getreceipt default response
func (o *GetreceiptDefault) WithPayload(payload *models.Error) *GetreceiptDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getreceipt default response
func (o *GetreceiptDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetreceiptDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
