package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListtimestampedHandlerFunc turns a function with the right signature into a listtimestamped handler
type ListtimestampedHandlerFunc func(ListtimestampedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListtimestampedHandlerFunc) Handle(params ListtimestampedParams) middleware.Responder {
	return fn(params)
}

// ListtimestampedHandler interface for that can handle valid listtimestamped params
type ListtimestampedHandler interface {
	Handle(ListtimestampedParams) middleware.Responder
}

// NewListtimestamped creates a new http.Handler for the listtimestamped operation
func NewListtimestamped(ctx *middleware.Context, handler ListtimestampedHandler) *Listtimestamped {
	return &Listtimestamped{Context: ctx, Handler: handler}
}

/*Listtimestamped swagger:route GET /horodatage listtimestamped

Liste les fichiers horodatés

Liste les fichiers horodatés


*/
type Listtimestamped struct {
	Context *middleware.Context
	Handler ListtimestampedHandler
}

func (o *Listtimestamped) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListtimestampedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
