// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "RCG horodatage est un service qui permet l'horodatage numérique via\nsur la blockchain Ethereum.\nLe principe est d'envoyer des fichiers qui sont ensuite passer dans\nune fonction hachage SHA3-256. Les « hash » sont ensuite intégrés\ndans un arbre de Merkle dont la racine est inséré dans une\ntransaction blockchain, l'(es) adresse(s) signant la transaction\nidentifie le Registre du Commerce, c'est une information qui doit\nêtre publique.\n",
    "title": "RCG horodatage - Validateur",
    "version": "0.1.0"
  },
  "paths": {
    "/status": {
      "get": {
        "description": "Retourne divers informations par le service\n",
        "summary": "Retourne des informations variés",
        "operationId": "getStatus",
        "responses": {
          "200": {
            "description": "Information document",
            "schema": {
              "$ref": "#/definitions/Informations"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Informations": {
      "type": "object",
      "properties": {
        "locked_key": {
          "type": "string"
        }
      }
    }
  }
}`))
}
