package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Informations informations
// swagger:model Informations
type Informations struct {

	// locked key
	LockedKey string `json:"locked_key,omitempty"`
}

// Validate validates this informations
func (m *Informations) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
