package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ReceiptFile receipt file
// swagger:model ReceiptFile
type ReceiptFile struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// horodatingaddress
	Horodatingaddress string `json:"horodatingaddress,omitempty"`

	// transactionhash
	Transactionhash string `json:"transactionhash,omitempty"`
}

// Validate validates this receipt file
func (m *ReceiptFile) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
