package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TodoFile todo file
// swagger:model TodoFile
type TodoFile struct {

	// available
	Available bool `json:"available,omitempty"`

	// filename
	// Required: true
	Filename *string `json:"filename"`

	// hash
	// Required: true
	Hash *string `json:"hash"`
}

// Validate validates this todo file
func (m *TodoFile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilename(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateHash(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TodoFile) validateFilename(formats strfmt.Registry) error {

	if err := validate.Required("filename", "body", m.Filename); err != nil {
		return err
	}

	return nil
}

func (m *TodoFile) validateHash(formats strfmt.Registry) error {

	if err := validate.Required("hash", "body", m.Hash); err != nil {
		return err
	}

	return nil
}
